FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --index-url https://pypi.iranserver.com/repository/pypi/simple -r requirements.txt

COPY ./app ./app

CMD ["celery", "-A", "app.tasks.worker", "worker", "--loglevel=info", "--beat"]
